# Brief illustration of how data is stored in Neural Networks

Scaler : 0 dimensional tensor

In [3]:
import numpy as np
X = np.array(12)
X

array(12)

In [4]:
X.ndim

0

1 dimensional array : 1 dimensional tensor

In [5]:
X = np.array([12, 3, 6, 14])
X.ndim

1

matrix or 2D array : 2 dimensional tensor

In [8]:
X = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
        [10,11,12]
    ]
)

X.ndim

2

In [11]:
import tensorflow as tf

2022-05-26 11:53:13.463309: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-05-26 11:53:13.465890: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-05-26 11:53:13.465897: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [22]:
tensor1 = tf.constant([[3,2], 
                      [5,2]])

tensor2 = tf.constant([[3,2], 
                       [5,2],
                       [5,2]
                      ])
# tensor.ndim
print("Shape of tensor1 : " , tf.shape(tensor1) )
print("Shape of tensor2 : " , tf.shape(tensor2) )
# print("\n\n")

Shape of tensor1 :  tf.Tensor([2 2], shape=(2,), dtype=int32)
Shape of tensor2 :  tf.Tensor([3 2], shape=(2,), dtype=int32)





In [23]:
print(tensor2)
print(tensor2.get_shape())
print(tensor2.shape.dims )

tf.Tensor(
[[3 2]
 [5 2]
 [5 2]], shape=(3, 2), dtype=int32)
(3, 2)
[Dimension(3), Dimension(2)]


In [33]:
arr_3d = np.random.randint(0, 100, size=(3, 4, 5))
arr_3d

array([[[18, 76,  5, 92,  7],
        [17, 66, 65, 50, 25],
        [18, 38, 13, 70, 25],
        [59, 42, 44, 14, 68]],

       [[37, 52, 26, 25, 18],
        [19, 15, 69, 62, 21],
        [86, 49, 85, 61, 84],
        [27, 44, 98, 15, 13]],

       [[32, 36, 70, 30,  5],
        [44, 12, 29,  2, 11],
        [23, 55, 72, 22, 71],
        [26, 78, 66, 47, 94]]])

In [35]:
tensor = tf.constant(arr_3d)
tensor

<tf.Tensor: shape=(3, 4, 5), dtype=int64, numpy=
array([[[18, 76,  5, 92,  7],
        [17, 66, 65, 50, 25],
        [18, 38, 13, 70, 25],
        [59, 42, 44, 14, 68]],

       [[37, 52, 26, 25, 18],
        [19, 15, 69, 62, 21],
        [86, 49, 85, 61, 84],
        [27, 44, 98, 15, 13]],

       [[32, 36, 70, 30,  5],
        [44, 12, 29,  2, 11],
        [23, 55, 72, 22, 71],
        [26, 78, 66, 47, 94]]])>

convert tensor object to numpy :

In [52]:
tensor.numpy()

array([[[18, 76,  5, 92,  7],
        [17, 66, 65, 50, 25],
        [18, 38, 13, 70, 25],
        [59, 42, 44, 14, 68]],

       [[37, 52, 26, 25, 18],
        [19, 15, 69, 62, 21],
        [86, 49, 85, 61, 84],
        [27, 44, 98, 15, 13]],

       [[32, 36, 70, 30,  5],
        [44, 12, 29,  2, 11],
        [23, 55, 72, 22, 71],
        [26, 78, 66, 47, 94]]])

In [51]:
#adds x to each element of tensor

# x = input()
x = 7
print("x = {}\n\n".format(x))

print("Before adding {} : \n".format(x))
print(tensor, end='\n\n')
tensor_add_1 = tf.add(tensor , x)

print("After adding {} : \n".format(x))
print(tensor_add_1)

x = 7


Before adding 7 : 

tf.Tensor(
[[[18 76  5 92  7]
  [17 66 65 50 25]
  [18 38 13 70 25]
  [59 42 44 14 68]]

 [[37 52 26 25 18]
  [19 15 69 62 21]
  [86 49 85 61 84]
  [27 44 98 15 13]]

 [[32 36 70 30  5]
  [44 12 29  2 11]
  [23 55 72 22 71]
  [26 78 66 47 94]]], shape=(3, 4, 5), dtype=int64)

After adding 7 : 

tf.Tensor(
[[[ 25  83  12  99  14]
  [ 24  73  72  57  32]
  [ 25  45  20  77  32]
  [ 66  49  51  21  75]]

 [[ 44  59  33  32  25]
  [ 26  22  76  69  28]
  [ 93  56  92  68  91]
  [ 34  51 105  22  20]]

 [[ 39  43  77  37  12]
  [ 51  19  36   9  18]
  [ 30  62  79  29  78]
  [ 33  85  73  54 101]]], shape=(3, 4, 5), dtype=int64)


reshape a tensor :

In [65]:
t = tensor_add_1

print( ('Before reshape : \n{}').format(t.numpy() ))
print('\nshape before reshape : {}\n\n'.format(t.get_shape() ) )

t = tf.reshape(tensor = t, shape=[3 , 20])

print( ('After reshape : \n{}').format(t.numpy() ))
print('\nshape after reshape : {}\n\n'.format(t.get_shape() ) )

Before reshape : 
[[[ 25  83  12  99  14]
  [ 24  73  72  57  32]
  [ 25  45  20  77  32]
  [ 66  49  51  21  75]]

 [[ 44  59  33  32  25]
  [ 26  22  76  69  28]
  [ 93  56  92  68  91]
  [ 34  51 105  22  20]]

 [[ 39  43  77  37  12]
  [ 51  19  36   9  18]
  [ 30  62  79  29  78]
  [ 33  85  73  54 101]]]

shape before reshape : (3, 4, 5)


After reshape : 
[[ 25  83  12  99  14  24  73  72  57  32  25  45  20  77  32  66  49  51
   21  75]
 [ 44  59  33  32  25  26  22  76  69  28  93  56  92  68  91  34  51 105
   22  20]
 [ 39  43  77  37  12  51  19  36   9  18  30  62  79  29  78  33  85  73
   54 101]]

shape after reshape : (3, 20)




In [72]:
t = tensor_add_1

print( ('Before reshape : \n{}').format(t.numpy() ))
print('\nshape before reshape : {}\n\n'.format(t.get_shape() ) )

# t = tf.reshape(tensor = t, shape=[2,2,3,5])
# t = tf.reshape(tensor = t, shape=[5,3,2,2])
t = tf.reshape(tensor = t, shape=[2,5,2,3])

print( ('After reshape : \n{}').format(t.numpy() ))
print('\nshape after reshape : {}\n\n'.format(t.get_shape() ) )

Before reshape : 
[[[ 25  83  12  99  14]
  [ 24  73  72  57  32]
  [ 25  45  20  77  32]
  [ 66  49  51  21  75]]

 [[ 44  59  33  32  25]
  [ 26  22  76  69  28]
  [ 93  56  92  68  91]
  [ 34  51 105  22  20]]

 [[ 39  43  77  37  12]
  [ 51  19  36   9  18]
  [ 30  62  79  29  78]
  [ 33  85  73  54 101]]]

shape before reshape : (3, 4, 5)


After reshape : 
[[[[ 25  83  12]
   [ 99  14  24]]

  [[ 73  72  57]
   [ 32  25  45]]

  [[ 20  77  32]
   [ 66  49  51]]

  [[ 21  75  44]
   [ 59  33  32]]

  [[ 25  26  22]
   [ 76  69  28]]]


 [[[ 93  56  92]
   [ 68  91  34]]

  [[ 51 105  22]
   [ 20  39  43]]

  [[ 77  37  12]
   [ 51  19  36]]

  [[  9  18  30]
   [ 62  79  29]]

  [[ 78  33  85]
   [ 73  54 101]]]]

shape after reshape : (2, 5, 2, 3)




In [83]:
dir(tf.keras.datasets)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_sys',
 'boston_housing',
 'cifar10',
 'cifar100',
 'fashion_mnist',
 'imdb',
 'mnist',
 'reuters']

observing fashion mnist dataset :

In [73]:
import tensorflow as tf
from tensorflow import keras

In [76]:
fashion_mnist = tf.keras.datasets.fashion_mnist

In [77]:
(training_image, training_label), (testing_image, testing_label) = fashion_mnist.load_data()

4422102/4422102 [==============================] - 1s 0us/step


In [92]:
print("number of dimensions of training samples : {}".format(training_image.ndim))
print("dimensions of training samples : {}\n\n".format(training_image.shape))

print("number of dimensions of testing samples : {}".format(testing_image.ndim))
print("dimensions of testing samples : {}\n\n".format(testing_image.shape))

print("number of dimensions of testing  labels : {}".format(training_label.ndim))
print("dimensions of testing labels : {}\n\n".format(training_label.shape))

print("number of dimensions of testing  labels : {}".format(testing_label.ndim))
print("dimensions of testing labels : {}\n\n".format(testing_label.shape))

number of dimensions of training samples : 3
dimensions of training samples : (60000, 28, 28)


number of dimensions of testing samples : 3
dimensions of testing samples : (10000, 28, 28)


number of dimensions of testing  labels : 1
dimensions of testing labels : (25000,)


number of dimensions of testing  labels : 1
dimensions of testing labels : (25000,)




In [100]:
# Visualize the first image from the training dataset
import matplotlib.pyplot as plt 
import random

id = random.randint((0,100))

plt.figure()
plt.imshow(training_image[id])
plt.colorbar()
plt.grid(False)

TypeError: randint() missing 1 required positional argument: 'b'